### ISSUE TITLE
Publish custom component for Home Assistant

### ISSUE THREAD

**Issue by theelog** [nicolasberthel/pybecker#1]
It's stated that the goal of this library is to be used in Home assistant custom component to control your becker shutters. But this component is not yet publicly released.

Any chance you can share what you have right now?

Update: I've got it working using the [cover.command_line](https://www.home-assistant.io/integrations/cover.command_line/) in Home Assistant.

Example:

```
cover:
  - platform: command_line
    covers:
      rollershutter:
        friendly_name: "Roller shutter"
        command_open: 'pybecker -a UP -c 1'
        command_close: 'pybecker -a DOWN -c 1'
        command_stop: 'pybecker -a HALT -c 1'
```
